### ISSUE TITLE
Error when reloading data from the same input folder

### ISSUE THREAD

**Issue by HenningEMBL** [tischi/fiji-script-registrationUsingElastix#20]
Hi,

in my hands, the script works fine as long as one selects a new input data folder each time the script is run. If I try to rerun the code on the same input folder, however, the first image loaded is not the one specified as reference frame (e.g. 100) but /2 (i.e. 50). This creates an error.
This issue cannot be overcome by (1) changing the output folder, (2) restarting Fiji, (3) renaming the input folder. Usually it helps to copy the input data into a new folder, sometimes I even had to regenerate the input data (i.e. write the input .czi file into a .tif image sequence)

Any idea how to solve this issue?
Thanks!

**Comment by tischi** [comment]
Hi,
I cannot reproduce the error. 
Are you using the latest version?

**Comment by HenningEMBL** [comment]
As far as I know, yes

---
Henning Falk, Ph.D. student
Aulehla Group
EMBL Heidelberg | Meyerhofstraße 1 | D-69117 Heidelberg | Germany
henning.falk@embl.de
+49 6221 387-8520

**Comment by HenningEMBL** [comment]
shall we have a try together on my machine?

---
Henning Falk, Ph.D. student
Aulehla Group
EMBL Heidelberg | Meyerhofstraße 1 | D-69117 Heidelberg | Germany
henning.falk@embl.de
+49 6221 387-8520

**Comment by tischi** [comment]
just download again to be sure:
https://github.com/tischi/fiji-registration/archive/master.zip

**Comment by tischi** [comment]
one currently cannot make the output folder inside the input folder
